# Generated by Django 5.1.7 on 2025-11-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
