# Generated by Django 5.1.7 on 2025-12-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventsentry_organizationentry_deadline_schedule_and_more'),
        ('api', '0005_event_link'),
    ]

    operations = [
    ]
