# Generated by Django 5.1.7 on 2026-01-09 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_events_usercalendarevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalendarevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.events'),
        ),
    ]
