# Generated by Django 5.1.7 on 2026-01-12 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=32)),
                ('fullName', models.CharField(blank=True, default='', max_length=32)),
                ('professor', models.CharField(blank=True, default='', max_length=64)),
                ('section', models.CharField(blank=True, default='', max_length=32)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('credit_hours', models.SmallIntegerField(blank=True, null=True)),
                ('meetingTimes', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
